version: '3.8'
services:
  project-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_DB}"
    networks:
      - myproject
networks:
    myproject: