version: '3.8'
services:
  project-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: nestdb
    networks:
      - myproject
networks:
    myproject:    